"""add alliance to user_profiles

Revision ID: 3fd615485238
Revises: ee7af091ee8f
Create Date: 2026-03-27 18:35:07.337042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd615485238'
down_revision: Union[str, Sequence[str], None] = 'ee7af091ee8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('alliance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'alliance')
    # ### end Alembic commands ###
