"""add mood scores to sessions

Revision ID: 616b8892c1a7
Revises: 3fd615485238
Create Date: 2026-03-28 07:06:06.192178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616b8892c1a7'
down_revision: Union[str, Sequence[str], None] = '3fd615485238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('opening_mood_score', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('closing_mood_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'closing_mood_score')
    op.drop_column('sessions', 'opening_mood_score')
    # ### end Alembic commands ###
