"""add case_formulations table

Revision ID: aff38d929e3b
Revises: db772f559771
Create Date: 2026-03-27 16:36:02.483469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff38d929e3b'
down_revision: Union[str, Sequence[str], None] = 'db772f559771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_formulations',
    sa.Column('formulation_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('readiness', sa.Text(), nullable=False),
    sa.Column('primary_issue', sa.Text(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('cognitive_patterns', sa.JSON(), nullable=True),
    sa.Column('emotional_state', sa.JSON(), nullable=True),
    sa.Column('behavioral_patterns', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('alliance_quality', sa.Text(), nullable=True),
    sa.Column('missing', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('formulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_formulations')
    # ### end Alembic commands ###
