"""add user_profiles table

Revision ID: db772f559771
Revises: 8aa9501f57bf
Create Date: 2026-03-27 15:15:09.435841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db772f559771'
down_revision: Union[str, Sequence[str], None] = '8aa9501f57bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
