"""add interventions table

Revision ID: ee7af091ee8f
Revises: aff38d929e3b
Create Date: 2026-03-27 17:13:28.858393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7af091ee8f'
down_revision: Union[str, Sequence[str], None] = 'aff38d929e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('target_issue', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('key_insight', sa.Text(), nullable=True),
    sa.Column('homework_assigned', sa.JSON(), nullable=True),
    sa.Column('homework_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    # ### end Alembic commands ###
